"""fix_enum

Revision ID: 0005
Revises: 0004
Create Date: 2025-10-18 14:38:43.695957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update the enum to include new values
    op.execute("ALTER TYPE employeerespondstatus ADD VALUE 'INTERVIEW_PENDING'")
    op.execute("ALTER TYPE employeerespondstatus ADD VALUE 'JOB_OFFER'")
    op.execute("ALTER TYPE employeerespondstatus ADD VALUE 'JOB_ACCEPTED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum type and updating all references
    # For now, we'll leave the new values in place
    pass
    # ### end Alembic commands ###
