name: Deploy Application

on:
  push:
    branches: [ trunk, add-back ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Compose with Sentry
      run: |
        cd deploy
        docker compose build

    - name: Run database migrations
      run: |
        cd deploy
        docker compose run professionmap-ats alembic upgrade head

    - name: Start services with Docker Compose
      run: |
        cd deploy
        docker compose up -d

    - name: Start services with Docker Compose
      run: |
        cd deploy
        docker compose up -d

    - name: Verify services are running
      run: |
        cd deploy
        docker compose ps